# https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-blue
  labels:
    app: nginx-blue
spec:
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
  selector:
    app: nginx-blue
  type: LoadBalancer
